[package]
name = "agent-concurrent-rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "agent_concurrent_core"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21.2", features = ["extension-module"] }
rayon = "1.10.0"