repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.3
    hooks:
    -   id: ruff
        args:
        - --fix
        - --exit-non-zero-on-fix
    -   id: ruff-format
-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: mypy
        language: system
        files: ^(agent-core/src|agent-engine/src|agent-concurrent/src|agent-persist/src)/
        args: [
            agent-core/src,
            agent-engine/src, 
            agent-concurrent/src,
            agent-persist/src
        ]
        pass_filenames: false