repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.3
    hooks:
    -   id: ruff
        args:
        - --fix
        - --exit-non-zero-on-fix
    -   id: ruff-format
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1
    hooks:
    -   id: mypy
        files: ^(agent-core/src|agent-engine/src|agent-concurrent/src|agent-persist/src)/
