# mkdocs.yml

site_name: Affective Reinforcement Learning Agents (ARLA)
site_url: https://renbytes.github.io/arla/
site_description: >-
  ARLA is a framework for building complex, multi-agent simulations
  with a focus on emergent behavior and artificial intelligence.
site_author: Bordumb / Renbytes
repo_url: https://github.com/renbytes/arla
repo_name: arla

docs_dir: docs

# Copyright
copyright: Copyright &copy; 2025 Bordumb / Renbytes

# Configuration
theme:
  name: material
  # logo: assets/logo.svg
  # favicon: assets/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Plugins
plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          setup_paths:
            - agent-core/src
            - agent-engine/src
            - agent-concurrent/src
            - agent-persist/src
            - agent-sim/src
          options:
            show_root_heading: true
            show_source: false
  - rss

extra:
  blog:
    authors_file: "{blog}/.authors.yml"
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/renbytes
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/arla/

# Page tree
nav:
  - Home: index.md
  - Tutorials:
    - "Building Your First Simulation": tutorials/first-simulation.md
  - User Guides:
    - "Installation & Setup": guides/installation.md
    - "Running Simulations": guides/running-simulations.md
    - "Understanding the Output": guides/understanding-output.md
  - Developer Guides:
    - "Architecture": architecture/index.md
    - "Creating a New Action": developer/creating-actions.md
    - "Creating a New System": developer/creating-systems.md
    - "The Event Bus": developer/event-bus.md
  - Contributor's Guide:
    - "Development Setup": contributing/setup.md
    - "Coding Standards & Style": contributing/style-guide.md
    - "Running Tests": contributing/testing.md
  - API Reference:
    - "agent-core": api/agent-core.md
    - "agent-engine": api/agent-engine.md
  - Blog: blog/index.md

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/renbytes
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/arla/ # When we publish it

# Markdown extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.tabbed: # Extension for content tabs (=== "title")
      alternate_style: true
  - pymdownx.emoji: # Extension for icons
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences: # Configuration block for Mermaid
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  - stylesheets/custom.css
