[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "agent-persist"
version = "0.1.0"
authors = [
  { name="Your Name", email="your@email.com" },
]
description = "A library for persisting and restoring agent-based simulation states."
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pydantic>=2.0"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff",
    "mypy",
    "pip-tools"
]

[project.urls]
"Homepage" = "https://github.com/renbytes/agent-persist"
"Bug Tracker" = "https://github.com/renbytes/agent-persist/issues"