[project]
name = "agent-engine"
version = "0.1.0"
description = "The world-agnostic simulation and cognitive systems for the agent platform."
authors = [{ name = "Your Name", email = "your@email.com" }]
requires-python = ">=3.11"
dependencies = [
    "numpy",
    "torch",
    "matplotlib",
    "omegaconf",
    "agent-core @ file:../agent-core"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-mock",
    "ruff",
    "mypy",
    "pip-tools",
]

[tool.ruff]
line-length = 120
