[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "agent-core"
version = "0.1.0"
description = "Core data structures and interfaces for the ARLA platform."
dependencies = [
    "numpy"
]

[tool.setuptools.packages.find]
where = ["src"]
