# .github/workflows/ci.yml

name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    name: "Build & Test"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Set up Python"
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.9"
          cache: "poetry"

      - name: "Install Graphviz"
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz graphviz-dev

      - name: "Install Poetry"
        uses: snok/install-poetry@v1

      - name: "Install dependencies"
        # The simple 'poetry install' command is the most robust way to install
        # all dependencies (main and dev) from the lock file.
        run: poetry install

      - name: "Run Linter & Formatter"
        run: |
          poetry run ruff check .
          poetry run ruff format --check .

      - name: "Run Type Checker"
        run: poetry run mypy agent-core agent-engine agent-concurrent agent-persist agent-sim simulations

      - name: "Run Tests"
        run: poetry run pytest