# .github/workflows/ci.yml

name: Python Application CI

# This workflow runs on every push to the 'main' branch and every pull request that targets 'main'.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    # Run the job on the latest version of Ubuntu
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your repository code so the workflow can access it
      - name: Check out code
        uses: actions/checkout@v4

      # 2. Set up the Python environment
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Install project dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff mypy pytest pytest-mock safety  # Explicitly install testing tools

      # 4. Lint with Ruff (checks for style and errors)
      - name: Lint with Ruff
        run: |
          ruff check .

      # 5. Check formatting with Ruff
      - name: Check formatting with Ruff
        run: |
          ruff format --check src/

      # 6. Run security scan with Safety
      # - name: Scan for vulnerabilities
      #   run: |
      #     safety check -r requirements.txt

      # 7. Run static type checking with Mypy
      - name: Type check with Mypy
        run: |
          mypy src/

      # 8. Run tests with Pytest
      - name: Test with Pytest
        run: |
          pytest
