# .github/workflows/docs.yml

name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-docs:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.9"

      - name: "Install Poetry"
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: "Configure Poetry"
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true

      - name: "Install dependencies with fallback"
        run: |
          # Try to install all dependencies first
          poetry install || {
            echo "Full install failed, trying without optional dependencies..."
            poetry install --no-dev --verbose
          } || {
            echo "Fallback: installing core dependencies only..."
            poetry install --only main --verbose
          }

      - name: "Build and deploy documentation"
        run: poetry run mkdocs gh-deploy --force