# .github/workflows/docs.yml

name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-docs:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.9"

      - name: "Install Graphviz system dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz graphviz-dev libgraphviz-dev pkg-config

      - name: "Install Poetry"
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: "Configure Poetry"
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true

      - name: "Cache Poetry dependencies"
        uses: actions/cache@v4
        with:
          path: .venv
          key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ runner.os }}-

      - name: "Install all project dependencies"
        run: poetry install

      - name: "Build and deploy documentation"
        run: poetry run mkdocs gh-deploy --force